### ISSUE TITLE
Rotenone meeting notes

### ISSUE THREAD

**Issue by jeremyshelton** [jeremyshelton/Jordan-FRC#3]
Create notes from meetings with DFFE (I have already done the DWS one).
Zoom recordings available [here](https://www.dropbox.com/scl/fo/shpytnywr5iafurkw6qnz/h?rlkey=l7f7xjkd9ewfk67fcuz92puvy&dl=0).
Example of meeting notes also available via that link.

**Comment by jeremyshelton** [comment]
Example of meeting notes:

[Biedouw Rotenone project_DWS meeting notes_2024 01 24.docx](https://github.com/jeremyshelton/Jordan-FRC/files/15020694/Biedouw.Rotenone.project_DWS.meeting.notes_2024.01.24.docx)

**Comment by jordancalder2** [comment]
[Biedouw Rotenone project_DFFE Notes.docx](https://github.com/jeremyshelton/Jordan-FRC/files/15074001/Biedouw.Rotenone.project_DFFE.Notes.docx)
