### ISSUE TITLE
Biedouw Restoration Project Update: Control Burn

### ISSUE THREAD

**Issue by jeremyshelton** [jeremyshelton/Jordan-FRC#4]
We need to send out a project update to Biedouw land owners (the 4 included in the burn, plus others downstream), project partners (CapeNature, Bushmans Kloof). This can include a summary of what was done, why it was done and what the outcome was. Introduction and context of the broader project into which it fits should also be provided up front. I will provide some photos.
Might be nice to do it on mail chimp so that the update page can be shared? Keen to hear your thoughts?

**Comment by jeremyshelton** [comment]
We need to send out a project update to Biedouw land owners (the 4 included in the burn, plus others downstream), project partners (CapeNature, Bushmans Kloof). This can include a summary of what was done, why it was done and what the outcome was. Introduction and context of the broader project into which it fits should also be provided up front. I will provide some photos.
Might be nice to do it on mail chimp so that the update page can be shared? Keen to hear your thoughts?

**Comment by jordancalder2** [comment]
Done with the first draft - its in the Biedouw project dropbox folder under COMMUNICATIONS

**Comment by jordancalder2** [comment]
Please can you send me email contacts when you can

**Comment by jordancalder2** [comment]
Mailchimp Newsletter sent on Tuesday the 7th of May
