### ISSUE TITLE
Project Update: Berg River Fish Survey

### ISSUE THREAD

**Issue by jeremyshelton** [jeremyshelton/Jordan-FRC#5]
We need a project update sent out to all of the contacts in the Berg about the Fish survey we did in March.
This can include what we did, what we found, and how it fits into the larger project.
It should probably begin with a brief introduction to and overview of the project.

**Comment by jordancalder2** [comment]
Hello, 

A draft for the Berg river update is in the Dropbox folder and also here: 

[Bringing Back the Witvis Update April 2024.docx](https://github.com/jeremyshelton/Jordan-FRC/files/15109574/Bringing.Back.the.Witvis.Update.April.2024.docx)

**Comment by jordancalder2** [comment]
Mailchimp complete, just needs to be sent

**Comment by jordancalder2** [comment]
Mailchimp newsletter sent on Tuesday the 14th of May
